### ISSUE TITLE
Consider shuttering the project

### ISSUE THREAD

**Issue by AArnott** [asmichi/StreamJsonRpcMessagePack#1]
Now that StreamJsonRpc 2.3 has MessagePack support built in, consider pushing a nuget package update to nuget.org with release notes or otherwise encouraging folks to use the officially supported MessagePackFormatter from StreamJsonRpc 2.3, and archiving this project.

No pressure of course. It's your project. But it's a suggestion.

**Comment by asmichi** [comment]
Fine. I will archive this project once the stable release of StreamJsonRpc 2.3 is out.

I'd appreciate it if you would let me know when the stable release is out.

**Comment by asmichi** [comment]
Closing. Now the packages are unlisted and the README clearly encourages migration.
